package l2tp

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/lucaswren/s2l/internal/model"
)

// xl2tpd 只认分号注释，不认 #（否则会报 occurs with no context）
const (
	confBegin = "; BEGIN s2l managed block - DO NOT EDIT"
	confEnd   = "; END s2l managed block"
)

// ConfManager 动态维护 /etc/xl2tpd/xl2tpd.conf
type ConfManager struct {
	path        string
	optionsPath string
	chapPath    string
	mu          sync.Mutex
}

func NewConfManager(path, optionsPath string, chapPath ...string) *ConfManager {
	if path == "" {
		path = "/etc/xl2tpd/xl2tpd.conf"
	}
	if optionsPath == "" {
		optionsPath = "/etc/ppp/options.xl2tpd"
	}
	cp := "/etc/ppp/chap-secrets"
	if len(chapPath) > 0 && chapPath[0] != "" {
		cp = chapPath[0]
	}
	return &ConfManager{path: path, optionsPath: optionsPath, chapPath: cp}
}

// Sync 重写完整可用的 xl2tpd.conf（避免示例注释文件干扰）
func (c *ConfManager) Sync(active []model.TunnelMapping) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if err := c.ensureOptions(); err != nil {
		return err
	}
	if err := os.MkdirAll("/var/run/xl2tpd", 0o755); err != nil {
		return err
	}

	content, err := renderFullConf(active, c.optionsPath, c.chapPath)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(c.path), 0o755); err != nil {
		return err
	}
	tmp := c.path + ".s2l.tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, c.path)
}

func (c *ConfManager) ensureOptions() error {
	if err := os.MkdirAll(filepath.Dir(c.optionsPath), 0o755); err != nil {
		return err
	}
	// 每次 Sync 覆盖。注意：部分 pppd/pppol2tp 组合不支持 lock
	content := `# generated by s2l - L2TP LNS
refuse-eap
refuse-pap
require-chap
require-mschap-v2
noccp
auth
proxyarp
nodefaultroute
mtu 1400
mru 1400
lcp-echo-interval 30
lcp-echo-failure 4
connect-delay 5000
`
	return os.WriteFile(c.optionsPath, []byte(content), 0o644)
}

func renderFullConf(active []model.TunnelMapping, optionsPath string, chapPath ...string) (string, error) {
	authPath := "/etc/ppp/chap-secrets"
	if len(chapPath) > 0 && chapPath[0] != "" {
		authPath = chapPath[0]
	}
	var b strings.Builder
	b.WriteString(confBegin + "\n")
	b.WriteString("; generated by s2l - xl2tpd comments must use ';'\n")
	b.WriteString("[global]\n")
	b.WriteString("port = 1701\n")
	b.WriteString(fmt.Sprintf("auth file = %s\n", authPath))
	b.WriteString("access control = no\n")
	b.WriteString("\n")

	b.WriteString("[lns default]\n")
	b.WriteString("ip range = 10.0.0.2-10.0.255.254\n")
	b.WriteString("local ip = 10.255.254.1\n")
	b.WriteString("require chap = yes\n")
	b.WriteString("refuse pap = yes\n")
	b.WriteString("require authentication = yes\n")
	b.WriteString("name = s2l\n")
	b.WriteString(fmt.Sprintf("pppoptfile = %s\n", optionsPath))
	b.WriteString("length bit = yes\n")
	b.WriteString("\n")

	if len(active) == 0 {
		b.WriteString("; (no active L2TP mappings)\n")
	} else {
		for _, m := range active {
			localIP, err := LocalIPFromSubnet(m.Subnet)
			if err != nil {
				return "", fmt.Errorf("mapping %s: %w", m.ID, err)
			}
			clientIP, err := ClientIPFromSubnet(m.Subnet)
			if err != nil {
				return "", fmt.Errorf("mapping %s: %w", m.ID, err)
			}
			b.WriteString(fmt.Sprintf("; map %s tun=%s table=%d user=%s peer=%s gw=%s\n",
				m.ID, m.TunName, m.TableID, m.L2TPUser, clientIP, localIP))
		}
	}
	b.WriteString(confEnd + "\n")
	return b.String(), nil
}
